### PR TITLE
Add CI/CD

### PR DESCRIPTION
**Pull request by R1KO**

### CODE REVIEW

**Review by CrazyHackGUT — APPROVED** [review]

**Comment by TiBarification** [comment]
What about https://github.com/hlmod/Shop-Core/blob/master/.travis.yml#L28-L32 ? I don't see it download dependencies like SteamWorks.

**Review by TiBarification — CHANGES_REQUESTED** [review]
Missing dependencies, is it build without SteamWorks ?

**Comment by R1KO** [comment]
> What about https://github.com/hlmod/Shop-Core/blob/master/.travis.yml#L28-L32 ? I don't see it download dependencies like SteamWorks.

I thought about it. I think it's worth adding. I'll take care of it today

**Review by TiBarification — APPROVED** [review]

**Comment by R1KO** [comment]
@TiBarification I fixed the build with SteamWorks

**Pull request merged**
